/**
 * The list of horror tropes for the bingo card.
 */
export default [
  'Turn On The Power',
  'Inconspicuous Button Spawns Monsters',
  'Basement or Sewer Mission',
  'Let\'s Split Up Just Because',
  'Flashlight Battery Lasts 5 Minutes',
  'Ramirez, Go Fix the Thing',
  'Useless Wooden Boxes',
  'Jump Scares',
  'First-Person Jumping Puzzles',
  'Zombies Because Why Not',
  'From Zero To Mass Murderer',
  'Audio Logs Interrupted By Spoop',
  'Terrible Final Boss Ruins Game',
  'Vengeful Child',
  'Timed Mission or Puzzle',
  'Exposition Dump',
  'Shotgun in Doctor\'s Office',
  'Broken Staircase',
  'Obvious Monster Closet',
  'Flickering Lights',
  'Abandoned Wheelchair',
  'Irrelevant Heartstrings Tugging',
  'Fake Doors or Broken Lock',
  'Super Soldier Creation Attempt',
  'Crazed German Scientist Villain',
  'MacGuffin Somehow Fixes Thing',
  'One Hit Player Kill',
  'Umbrella or Weyland-Yutani Ripoff',
  'Villain Has Savior Delusion',
  'I Did It To Help',
  'Annoying Companion NPC',
  'Bloody Letters',
  'Random Pollock Blood Spatters',
  'Generic Brown or Grey Corridors',
  'Backlit'
];
